// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhxaakaeqwefnmguthet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oeGFha2FlcXdlZm5tZ3V0aGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzM1MTUsImV4cCI6MjA2NTUwOTUxNX0.L-mn5kKXLdjve2VZLqzPSSqMdGw216FBvF2rHA6BswA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);